
services:
  cli:
    build:
      context: ./docker/worker
    command: "python cli.py"
    env_file:
      - ./app.env
    volumes:
      - ./worker:/app
      - ./data/backend:/data
    depends_on:
      - sam2
      - openpose
    restart: on-failure
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [ gpu ]

  sam2:
    build:
      context: ./docker/sam2
    command: "uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --root-path /api/"
    env_file:
      - ./app.env
    volumes:
      - ./sam2:/app
    restart: on-failure
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [ gpu ]

  openpose:
    build:
      context: ./docker/openpose
    command: "uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --root-path /api/"
    env_file:
      - ./app.env
    volumes:
      - ./openpose:/app
      - ./docker/openpose/models:/models
    restart: on-failure
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [ gpu ]
