
services:
  proxy:
    image: ${DOCKER_REGISTRY}proxy:${DOCKER_TAG}
    build:
      context: ./docker_build/proxy
      dockerfile: Dockerfile

  frontend:
    image: ${DOCKER_REGISTRY}frontend:${DOCKER_TAG}
    build:
      context: .
      dockerfile: docker_build/frontend/Dockerfile

  postgres:
    image: ${DOCKER_REGISTRY}postgres:${DOCKER_TAG}
    build:
      context: ./docker_build/postgres
      dockerfile: Dockerfile

  keycloak:
    image: ${DOCKER_REGISTRY}keycloak:${DOCKER_TAG}
    build:
      context: ./docker_build/keycloak
      dockerfile: Dockerfile

  backend:
    image: ${DOCKER_REGISTRY}backend:${DOCKER_TAG}
    build:
      context: .
      dockerfile: docker_build/backend/Dockerfile

  worker:
    image: ${DOCKER_REGISTRY}worker:${DOCKER_TAG}
    build:
      context: .
      dockerfile: docker_build/worker/Dockerfile

  sam2:
    image: ${DOCKER_REGISTRY}sam2:${DOCKER_TAG}
    build:
      context: .
      dockerfile: docker_build/sam2/Dockerfile

  openpose:
    image: ${DOCKER_REGISTRY}openpose:${DOCKER_TAG}
    build:
      context: .
      dockerfile: docker_build/openpose/Dockerfile
