version: '3'

services:
  proxy:
    image: ${DOCKER_REGISTRY}proxy:${DOCKER_TAG}
    build:
      context: ./docker_build/proxy
      dockerfile: Dockerfile

  frontend:
    image: ${DOCKER_REGISTRY}frontend:${DOCKER_TAG}
    build:
      context: .
      dockerfile: docker_build/frontend/Dockerfile

  postgres:
    image: ${DOCKER_REGISTRY}postgres:${DOCKER_TAG}
    build:
      context: ./docker_build/postgres
      dockerfile: Dockerfile

  keycloak:
    image: ${DOCKER_REGISTRY}keycloak:${DOCKER_TAG}
    build:
      context: ./docker_build/keycloak
      dockerfile: Dockerfile

  backend:
    image: ${DOCKER_REGISTRY}backend:${DOCKER_TAG}
    build:
      context: .
      dockerfile: docker_build/backend/Dockerfile

# @todo this is too heavy to build in CI; Try to make the worker more light-weight and buildable in CI
#  worker_basic:
#    image: ${DOCKER_REGISTRY}worker_basic:${DOCKER_TAG}
#    build:
#      context: .
#      dockerfile: docker_build/worker_basic/Dockerfile
