RESULT_BASE_PATH = "data/results"
VIDEOS_BASE_PATH = "data/videos"
PRESETS_BASE_PATH = "data/presets"

AUTH_TOKEN_ISSUER = "https://localhost/auth/realms/maskanyone"
AUTH_TOKEN_AUDIENCE = "account"
AUTH_ALGORITHM = "RS256"
AUTH_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXeGEI7KQxGGA9fl8ISWvTu9K6ggPL886mU83kOxAqqSoSDnaG5CT3UbYqcgTmN4UNv5KMrdtqLvTOEWVo5ZBF48HHTUNDin20M6GNIQKPeQwTiY7H2vhjmcWabvchkjS8lKoMkheCZ5HJjsW+j+u6GgF0N/mloN2UgnejlTRUMMTpWA/Mr2TGbn8Yzxqtyiab/ywuAcWema5KfpqXdCCErcHqMjy0LXAJ70C2rXlgO8cC8nL49cRkNncpdXl3I9e9mNSBGwIP6WqVVBh6OmlOdIK94ALzJH3UeweAufqhw7jbGILj3YKr0o08lWuSTn9e28BpD0h8iIymY5h9LvlQIDAQAB
-----END PUBLIC KEY-----"""
