FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app


RUN apt-get update \
    && apt-get -y install \
    python3 \
    python3-pip \
    python-is-python3 \
    python3-opencv \
    libgl1 \
    libglib2.0-0 \
    libpq-dev \
    gcc \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

RUN git clone https://github.com/mkocabas/VIBE.git
RUN cd VIBE

RUN conda create -n vibe python=3.7
RUN source activate vibe && pip install torch==1.4.0 numpy==1.17.5
RUN source activate vibe && pip install git+https://github.com/giacaglia/pytube.git --upgrade
RUN pwd
RUN source activate vibe && pip install -r requirements.txt
RUN scripts/prepare_data.sh
