FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -y install \
    python3 \
    python3-pip \
    python-is-python3 \
    python3-opencv \
    libgl1 \
    libglib2.0-0 \
    libpq-dev \
    gcc \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN pip install pyyaml==5.2
RUN pip install scipy
RUN pip install numpy
RUN pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113

RUN cd /AlphaPose
RUN git clone https://github.com/MVIG-SJTU/AlphaPose.git

RUN python -m pip install cython
RUN sudo apt-get install libyaml-dev

RUN cd /content/AlphaPose
RUN python setup.py build develop

RUN pip install -U -q PyDrive
RUN mkdir /content/AlphaPose/detector/yolo/data
RUN mkdir /content/AlphaPose/detector/tracker/data
RUN wget -P ./detector/yolox/data/ https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.0/yolox_x.pth

RUN cd/content/AlphaPose