RESULT_BASE_PATH = "/local_data/results"
VIDEOS_BASE_PATH = "/local_data/original"
TS_BASE_PATH = "/local_data/timeseries"
BLENDSHAPES_BASE_PATH = "/local_data/blendshapes"
TEMP_PATH = "/local_data/temp"
IMPLEMENTED_VIDEO_PARTS = ["body", "face", "background"]
DATA_BASE_DIR = "/local_data"
DOCKER_MODELS_CONFIG_PATH = "/app/docker_worker/configs"
AVAILABLE_DOCKER_MODELS = ["roop", "blender"]
